import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "NextJs Tutorial",
    template: "%s | NextJs Tutorial",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{ background: "lightblue", padding: "1rem" }}
        >Header</header>
        {children}
        <footer style={{ background: "lightgreen", padding: "1rem" }}>Footer</footer>
      </body>
    </html>
  );
}
